FROM php:7.3-alpine
RUN docker-php-ext-install pdo pdo_mysql
RUN apk add composer
WORKDIR '/app'
COPY . .
RUN composer install
RUN mv .env.docker .env
RUN php artisan key:generate
CMD php artisan serve --host=0.0.0.0 --port=8000