version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'car-rental-api'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    links:
      - db:db
    volumes:
      - /app/vendor
      - .:/app