FROM php:7.3-alpine
RUN docker-php-ext-install pdo pdo_mysql
RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \ 
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && apk del pcre-dev ${PHPIZE_DEPS}
RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini;
RUN apk add composer
WORKDIR '/app'
COPY . .
RUN composer install
RUN mv .env.docker .env
RUN php artisan key:generate
CMD php artisan serve --host=0.0.0.0 --port=8000